<?php

namespace AppBundle\Repository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends \Doctrine\ORM\EntityRepository
{
}
