<?php

namespace AppBundle\Repository;

/**
 * MountaineerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MountaineerRepository extends \Doctrine\ORM\EntityRepository
{
}
